Fix missing manifest file for mono nuget
WARNING: fus-image-mono-1.0-r0 do_rootfs: Manifest ...
manifest-x86_64_x86_64-nativesdk-nuget.package_write_rpm not found in
fsimx8mm aarch64-mx8mm aarch64 allarch x86_64_x86_64-nativesdk (variant
'')?

ERROR: fus-image-mono-1.0-r0 do_rootfs: No manifest generated from:
nuget in ... nuget_3.5.0.bb